### ISSUE TITLE
View checkboxes

### ISSUE THREAD

**Issue by Czapa10** [CaptainTimberTim/MPlay3#2] opened 2021-03-11 20:06 UTC
Hi!
I almost always use only songs column.
It would be nice to have checkboxes to disable columns.
Right now I have to shrink left side columns every time I start up the program.
The values set by those checkboxes ought to be saved in some file when I change them and loaded on start up.

![image](https://user-images.githubusercontent.com/39434914/110846650-5101f280-82ac-11eb-8e45-db53109ff145.png)

**Comment by CaptainTimberTim** [comment] 2021-03-12 20:04
Hi,
I may add that in the future, but that will be a while. 

But you made me aware of a small bug with this, because I actually already save the width
of the columns and it only fails when they are crammed to one side, like you do.
This bug is now fixed in the new release and I also implemented your suggestions about embedding the resources and
not displaying null (null) in  the title bar, when a song is playing that has no metadata (which was the cause).

Meaning you should only need to push them to the side once and then never again, except when the settings file is deleted.

**Closed as completed by CaptainTimberTim** 2021-03-12 20:04 UTC

**Comment by Czapa10** [comment] 2021-03-13 01:07
Thank you for releasing new version so quickly. I really enjoy using your program.
Actually I really like the idea of window title being the name and author of song.
You could make window title be the name of the file if the file doesn't have metadata.
